version: "3.7"
services:
  postgres:
    build:
      context: .
      dockerfile: docker/Dockerfile.postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      net_postgres:
        ipv4_address: 172.16.18.2

  pgAdmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.postgres.org
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - 8080:80
    networks:
      net_postgres:
        ipv4_address: 172.16.18.3

  elixir:
    build:
      context: .
      dockerfile: docker/Dockerfile.elixir
    container_name: elixir
    image: elixir
    depends_on:
      - postgres
      - pgAdmin4
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: project
      DB_HOST: postgres
      SERVER_PORT: 4000
    ports:
      - 4000:4000
    volumes:
      - "./:/opt/app"
    networks:
      net_postgres:
        ipv4_address: 172.16.18.4

networks:
  net_postgres:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.18.0/24
