FROM elixir:latest

ENV APP_HOME /opt/app

RUN mix local.hex --force \
    && mix archive.install --force hex phx_new 1.4.11 \
    && apt-get update \
    && apt-get install -y apt-utils \
    && apt-get install -y build-essential \
    && apt-get install -y inotify-tools \
    && mix local.rebar --force

WORKDIR $APP_HOME
COPY . $APP_HOME

RUN mix deps.get
# RUN mix ecto.setup
RUN mkdir -p $APP_HOME

EXPOSE 4000

CMD ["mix", "phx.server"]
